### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by plamenkoyovchev** [doino-gretchenliev/revolut-stocks#22]
```
 Traceback (most recent call last):
revolut-stocks-calc_1  |   File "stocks.py", line 51, in <module>
revolut-stocks-calc_1  |     main()
revolut-stocks-calc_1  |   File "stocks.py", line 41, in main
revolut-stocks-calc_1  |     process(
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/process.py", line 62, in process
revolut-stocks-calc_1  |     statements[parser_name] = supported_parsers[parser_name](parser_input_dir).parse()
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parsers/revolut.py", line 188, in parse
revolut-stocks-calc_1  |     statements = sorted(statements, key=lambda k: k[self.get_first_non_ssp_activity_index(k)]["trade_date"])
revolut-stocks-calc_1  |   File "/usr/src/stocks/libs/parsers/revolut.py", line 188, in <lambda>
revolut-stocks-calc_1  |     statements = sorted(statements, key=lambda k: k[self.get_first_non_ssp_activity_index(k)]["trade_date"])
revolut-stocks-calc_1  | TypeError: list indices must be integers or slices, not NoneType
```

Executed with docker-compose command.

**Comment by doino-gretchenliev** [comment]
Please, provide more information about the issue. Refer to [bug reporting remplate](https://github.com/doino-gretchenliev/revolut-stocks/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) for the required information.

**Comment by plamenkoyovchev** [comment]
One of the exported pdf files was causing the issue. I've excluded it from the process and everything went well.
Unfortunately I can't give it to you because there is a lot of personal information in the file.

**Comment by doino-gretchenliev** [comment]
I'm closing the issue as there is no additional information.
